<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='css/thatsmyband.css' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body class="thatsmyband_backgroundColor">
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="col-xs-12 jumbotron">
                    <header align="center">
                        <p> That's My Band </p>
                    </header>
                </div>
            </div>
            <div class="row-fluid">
                <p><?= include(htmlspecialchars($subTemplate)); ?></p>
            </div>
        </div>
        <footer class="navbar-fixed-bottom"> <?php include('subtemplates/menuTemplate.phtml'); ?>  </footer>
    </body>
</html>