<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='css/thatsmyband.css' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body class="thatsmyband_backgroundColor">
        <div class="container-fluid">

            <header> <?php include('subtemplates/headerTemplate.phtml'); ?>  </header>

            <div class="row-fluid">
                <p><?= include(htmlspecialchars($subTemplate)); ?></p>
            </div>

            <footer class="navbar-fixed-bottom"> <?php include('subtemplates/menuTemplate.phtml'); ?>  </footer>
        </div>
    </body>
</html>