<div class="row">
	<div class="col-xs-6" align="left">
		<p>Band's event execution</p>
	</div>
	<div class="col-xs-6" align="right">
		<p> Band's current time : <?= htmlspecialchars($user->CurrentTime) ?></p>
	</div>
</div>

<div class="row">
	<div class="col-xs-6" align="left">
		<p>Event Type : <?= htmlspecialchars($event->Type) ?> </p>
	</div>
</div>

<div class="row">
	<div class="col-xs-6" align="left">
		<p>Band before Event : <?= print_r($event->Result->BandBeforeEvent) ?> </p>
	</div>
</div>

<div class="row">
	<div class="col-xs-6" align="left">
		<p>Band after Event : <?= print_r($user->Band) ?> </p>
	</div>
</div>