<div class="container thatsmyband_backgroundColor">
	
	<div class="col-xs-4">
		<div class="thatsmyband_roundButton">
			<a href="user">
				<img src="resources/images/userButton.png"/>
			</a>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="thatsmyband_roundButton">
			<a href="band">
				<img src="resources/images/bandButton.png"/>
			</a>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="thatsmyband_roundButton">
			<a href="schedule">
				<img src="resources/images/scheduleButton.png"/>
			</a>
		</div>
	</div>

</div>