<div class="container">
	<div class="row">
		<div class="container thatsmyband_backgroundColor">
			<div class="col-xs-4" align="center">
				<div class="thatsmyband_roundButton">
					<a href="user">
						<img class="img-circle img-responsive" src="resources/images/userButton.png"/>
					</a>
				</div>
			</div>

			<div class="col-xs-4" align="center">
				<div class="thatsmyband_roundButton">
					<a href="band">
						<img class="img-circle img-responsive" src="resources/images/bandButton.png"/>
					</a>
				</div>
			</div>

			<div class="col-xs-4" align="center">
				<div class="thatsmyband_roundButton">
					<a href="schedule">
						<img class="img-circle img-responsive" src="resources/images/scheduleButton.png"/>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>