<div class="row">
	<div class="col-xs-6" align="left">
		<p>Band's schedule</p>
	</div>
	<div class="col-xs-6" align="right">
		<p> Band's current time : <?= htmlspecialchars($user->CurrentTime) ?></p>
	</div>
</div>

<div class="row">
	<div class="col-xs-6" align="left">
		<img class="img-circle img-responsive" src="resources/images/addButton.png"/>
	</div>
	<div class="col-xs-6" align="right">
		<a href="executeEvent">
			<img class="img-circle img-responsive" src="resources/images/nextButton.png"/>
		</a>
	</div>
</div>

<?php
	$maxEventNumber = "0";
	foreach ($user->Band->Schedule->GenericEvents as $key => $event) { 
		if ($key >= $user->CurrentTime) {	?>
		<div class="row thatsmyband_avatarCard">
			<div class="col-xs-4" align="center">
			   	<img class="img-circle img-responsive" src="resources/images/defaultScheduleEvent.png"/>
			</div>
			<div class="col-xs-8">
				<p><b><?= htmlspecialchars($key); $maxEventNumber = $key + 1; ?></b></p>
				<p><b><?= htmlspecialchars($event->Id); ?></b></p>
			</div>
		</div>	
<?php }	
	} 
	if($user->CurrentTime > $maxEventNumber)
		$maxEventNumber = $user->CurrentTime;
	?>