<p><?= htmlspecialchars($user->Band->Schedule->Id); ?></p>

<?php
	$maxEventNumber = "0";
	foreach ($user->Band->Schedule->GenericEvents as $key => $event) { 
		if ($key >= $user->CurrentTime) {	?>
		<div class="row thatsmyband_avatarCard">
			<div class="col-xs-4" align="center">
			    <img class="img-circle img-responsive" src="resources/images/defaultScheduleEvent.png"/>
			</div>
			<div class="col-xs-8">
				<p><b><?= htmlspecialchars($key); $maxEventNumber = $key + 1; ?></b></p>
				<p><b><?= htmlspecialchars($event->Id); ?></b></p>
			</div>
		</div>	
<?php }	
	} 
	if($user->CurrentTime > $maxEventNumber)
		$maxEventNumber = $user->CurrentTime;
	?>
	
	<div class="row thatsmyband_avatarCard">

		<div class="col-xs-4" align="center">
			    <img class="img-circle img-responsive" src="resources/images/addButton.png"/>
			</div>
			<div class="col-xs-8">
				<p><b><?= htmlspecialchars($maxEventNumber); ?></b></p>
			</div>

	</div>